"""
Django settings for send_mail_prod project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e%g#!x3#bi(64d00)5)j+w@pkhho(_04%&95ysdq84_lg$o)7)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_inlinecss',

    'send_email',

    # для сброса пароля
    'reset_password_app'
    
    # для aws:
    # 'crispy_forms',
    # 'simple_email_confirmation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'send_mail_prod.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'send_mail_prod.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "media/")

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media/", 'img')

MEDIA_URL = '/test-email/images/'  # для отправки и использования наших статик файлов. /test-email/ - это то что идет после \
# нашего домента и /images/ мы харкордно в hello_email.html указываем <img src="images/bg_5.jpg" что бы прогрузилось (именно \
# на нашем сайте, но при отправки письма)

# 1)MAILCHIMP CONFIG
# https://us11.admin.mailchimp.com/account/add-api-key/
# pip install mailchimp-marketing
# http://i.imgur.com/4R9B8i8.png
MAILCHIMP_API_KEY = "c45f3e098a8952de2fec892f1f7ded75-us11"
MAILCHIMP_DATA_CENTER = "us11"  # последние цифры MAILCHIMP_API_KEY
MAILCHIMP_EMAIL_LIST_ID = "34a01c83db"


# 2)EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # для настройки будем использовать консоль вместо smtp, \
# но потом надо перенастроить

# 2.1)GMAIL CONFIG
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'nickolay.varvonets@gmail.com'
EMAIL_HOST_PASSWORD = 'sxemlitjlitvwvyd'  # пароль берем из настроек gmail при создании нового приложения
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'bolageg975@cupbest.com'


# 2.2)AWS CONFIG - такая же отправка писем как через GMAIL CONFIG, но сейчас через aws. Минус этого что он платный, если хотим\
# отправлять к неопозананным пользователеям(тех что не указали в настройках aws, те что не ified by aws)
# DEFAULT_FROM_EMAIL = 'itvdn.django2@gmail.com'

# EMAIL_USE_TLS = True
# EMAIL_HOST = 'email-smtp.us-east-2.amazonaws.com'
# EMAIL_HOST_USER = 'AKIA5ZT43BP5LNAO3QTY'
# EMAIL_HOST_PASSWORD = 'BFzrmpzbO6qEQc3yP8hcSYD5f2f/E8R/MBLxk6YEcQq6'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
